import type { Metadata } from "next";
import { Poppins, Noto_Sans_JP } from "next/font/google";
import 'sanitize.css';
import 'sanitize.css/forms.css';
import 'sanitize.css/typography.css';
import '../styles/globals.css';
import Navigation from "@/components/Navigation/Navigation";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  // subsets: ["latin", "japanese"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "700"],
  // subsets: ["latin"],
  // subsets: ["english", "japanese"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${notoSansJP.variable}`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}

