import type { Metadata } from "next";
import { Poppins, Noto_Sans_JP } from "next/font/google";
import 'sanitize.css';
import 'sanitize.css/forms.css';
import 'sanitize.css/typography.css';
import '../styles/globals.css';
import Navigation from "@/components/Navigation/Navigation";
import Icons from "@/components/Icons/Icons";
import Footer from "@/components/Footer/Footer";
import ContentsArea from "@/components/ContentsArea/ContentsArea";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  weight: ["400", "900"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${notoSansJP.variable}`}>
        <Icons />
        <Navigation />
        <ContentsArea>{children}</ContentsArea>
        <Footer />
      </body>
    </html>
  );
}